# Example: Application with Egress Sidecar
# This deployment allows your application to access Netmaker services
# using netclient + proxy sidecars in the same pod

apiVersion: v1
kind: Secret
metadata:
  name: netclient-token
  namespace: default
type: Opaque
stringData:
  token: "your-netclient-token-here"  # Replace with your actual token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-egress-sidecar
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      # Your application container
      - name: app
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait for egress proxy to be ready
          sleep 10
          
          # Your app connects to localhost:8080 (egress proxy sidecar)
          # The proxy forwards to the Netmaker service
          echo "Testing egress proxy..."
          while true; do
            curl -s http://localhost:8080/api/health || echo "Connection failed, retrying..."
            sleep 30
          done
        env:
        # App connects to localhost where egress proxy listens
        - name: EXTERNAL_API_URL
          value: "http://localhost:8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      
      # Netclient sidecar - provides WireGuard connectivity to Netmaker network
      - name: netclient
        image: gravitl/netclient:v1.2.0
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: netclient-token
              key: token
        - name: DAEMON
          value: "on"
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: netclient-config
          mountPath: /etc/netclient
        - name: netclient-logs
          mountPath: /var/log
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ip link show netmaker && ip addr show netmaker | grep inet"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      
      # Egress proxy sidecar - forwards from app to Netmaker device
      - name: egress-proxy
        image: alpine/socat:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Starting egress proxy sidecar..."
          
          # Wait for netclient to establish WireGuard interface
          echo "Waiting for WireGuard interface..."
          for i in $(seq 1 60); do
            if ip addr show netmaker 2>/dev/null | grep -q 'inet '; then
              echo "WireGuard interface ready"
              break
            fi
            sleep 1
          done
          
          # Get target from environment variables
          NETMAKER_TARGET_IP="${NETMAKER_TARGET_IP:-10.0.0.100}"
          NETMAKER_TARGET_PORT="${NETMAKER_TARGET_PORT:-8080}"
          PROXY_LISTEN_PORT="${PROXY_LISTEN_PORT:-8080}"
          
          NETMAKER_TARGET="$NETMAKER_TARGET_IP:$NETMAKER_TARGET_PORT"
          echo "Starting egress proxy: localhost:$PROXY_LISTEN_PORT -> $NETMAKER_TARGET"
          
          # Start socat to forward from localhost to Netmaker device
          exec socat TCP-LISTEN:$PROXY_LISTEN_PORT,bind=127.0.0.1,reuseaddr,fork TCP:$NETMAKER_TARGET
        env:
        # Configuration: Netmaker device to connect to
        - name: NETMAKER_TARGET_IP
          value: "10.0.0.100"  # Netmaker device IP address
        - name: NETMAKER_TARGET_PORT
          value: "8080"        # Port on Netmaker device
        - name: PROXY_LISTEN_PORT
          value: "8080"        # Port proxy listens on (app connects here)
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
        # Health check
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "netstat -tuln | grep -q ':8080 ' || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 30
      
      volumes:
      - name: netclient-config
        emptyDir: {}
      - name: netclient-logs
        emptyDir: {}
---
# Optional: Service for internal cluster access
apiVersion: v1
kind: Service
metadata:
  name: my-app-egress-sidecar
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-app
  type: ClusterIP

