# Example: Expose Netmaker API Service to Kubernetes Cluster
# This Service creates an egress proxy that routes traffic to a Netmaker device

apiVersion: v1
kind: Service
metadata:
  name: netmaker-api-egress
  namespace: default
  annotations:
    # Enable egress proxy functionality
    netmaker.io/egress: "enabled"
    # Option 1: Use Netmaker device IP address
    netmaker.io/egress-target-ip: "100.93.135.2"
    # Option 2: Use Netmaker device DNS name (uncomment to use DNS instead)
    # netmaker.io/egress-target-dns: "api.netmaker.internal"
    # Optional: Custom secret configuration for netclient token
    # Note: Secrets are always read from operator namespace (netmaker-k8s-ops-system) for security
    # netmaker.io/secret-name: "custom-netclient-token"      # Default: netclient-token
    # netmaker.io/secret-key: "token"                         # Default: token
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082  # This is the port on the Netmaker device (standard Kubernetes way)
    protocol: TCP
  # Note: The selector is optional - the controller manages endpoints directly
  # But including it helps with Service discovery
  selector:
    app: netmaker-egress-proxy
    service-name: netmaker-api-egress
  type: ClusterIP
---
# Example: Usage - Pod accessing Netmaker service via egress proxy
apiVersion: v1
kind: Pod
metadata:
  name: test-egress-access
  namespace: default
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command:
    - /bin/sh
    - -c
    - |
      echo "Testing egress proxy access..."
      # Retry until successful
      until curl -k -f http://netmaker-api-egress.default.svc.cluster.local:8082; do
        echo "Connection failed, retrying in 5 seconds..."
        sleep 5
      done
      echo "Successfully connected to egress proxy!"
      # Access Netmaker DB (example)
      # psql -h netmaker-db-egress.default.svc.cluster.local -U postgres
      sleep 3600
  restartPolicy: Never

